networks:
  slnet:
    name: slnet
    driver: bridge
    attachable: false

volumes:
  ringbuffer-data:
    driver: local

services:
  ringserver:
    build:
      context: ./ringserver
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "18000"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - slnet
    ports:
      - "18000:18000"
    volumes:
      - ringbuffer-data:/ringserver/ring
    entrypoint:
      /opt/ringserver/ringserver -v -Rd /ringserver/ring -Rs 100000000 -L 18000

  playback:
    build:
      context: ./playback
    depends_on:
      ringserver:
        condition: service_healthy
    networks:
      - slnet
    volumes:
      - ringbuffer-data:/ringserver/ring
      - ./mseed_files:/mseed_files
    environment:
      - MSEED_FILE=2025.001.WEL.10-HHZ.NZ.D
    entrypoint:
      python playback.py

  client:
    build:
      context: ./seedlink_client
    depends_on:
      ringserver:
        condition: service_healthy
    networks:
      - slnet
    entrypoint: 
      python seedlink_client.py